In [1]:
import numpy as np

In [4]:
test_input = np.array(
    [[0.0, 4.5, 2.0, 0.0, 3.0],
    [4.0, 0.0, 3.5, 0.0, 0.0],
    [0.0, 5.0, 0.0, 2.0, 1.3],
    [0.0, 3.5, 4.0, 1.0, 0.0]]
)
test_input

array([[ 0. ,  4.5,  2. ,  0. ,  3. ],
       [ 4. ,  0. ,  3.5,  0. ,  0. ],
       [ 0. ,  5. ,  0. ,  2. ,  1.3],
       [ 0. ,  3.5,  4. ,  1. ,  0. ]])

In [58]:
np.argwhere(test_input!=0)

array([[0, 1],
       [0, 2],
       [0, 4],
       [1, 0],
       [1, 2],
       [2, 1],
       [2, 3],
       [2, 4],
       [3, 1],
       [3, 2],
       [3, 3]])

![image.png](attachment:image.png)

In [62]:
class SVD_decomposer():
    def __init__(self, matrix):
        self.M = matrix
        self.r = 2
        
        #Our two decomposed matrices
        self.P = np.ones([self.M.shape[0], self.r])
        self.Q = np.ones([self.r, self.M.shape[1]])
        
        #Regularization parameter
        self.lambda_ = 0.2
        
        # Learning rates
        self.alpha = 0.05
        self.beta = 0.05
        
        # Keep indices of where we have entries
        self.entries_idx = np.argwhere(test_input != 0)
        
    def compute_loss(self):
        SSE = (np.matmul(self.P, self.Q) - self.M)**2
#         REG = self.lambda_ * (np.sum(self.P**2) + np.sum(self.Q**2))
        return np.sum(SSE)
    
    def SGD(self):
        #Generate two random indices
        np.random.shuffle(self.entries_idx)
        u,i = self.entries_idx[0]
#         np.random.randint(0, self.P.shape[0]), np.random.randint(0, self.Q.shape[1])
        
        self.P[u] = self.P[u] + self.alpha * np.dot(self.Q[:,i], (self.M[u,i] - np.dot(self.P[u], self.Q[:,i])))
        self.Q[:,i] = self.Q[:,i] + self.beta * np.dot(self.P[u], (self.M[u,i] - np.dot(self.P[u], self.Q[:,i])))

        

In [63]:
model = SVD_decomposer(test_input)

for i in range(2000):
    model.SGD()
    print (model.P)
    print()
    print (model.Q)
    print()
    print (np.matmul(model.P,model.Q))
    print("Loss: {}".format(model.compute_loss()))
    print('---------------------------------------------')

[[1.  1. ]
 [1.1 1.1]
 [1.  1. ]
 [1.  1. ]]

[[1.099 1.    1.    1.    1.   ]
 [1.099 1.    1.    1.    1.   ]]

[[2.198  2.     2.     2.     2.    ]
 [2.4178 2.2    2.2    2.2    2.2   ]
 [2.198  2.     2.     2.     2.    ]
 [2.198  2.     2.     2.     2.    ]]
Loss: 69.19696884
---------------------------------------------
[[1.    1.   ]
 [1.1   1.1  ]
 [1.    1.   ]
 [1.075 1.075]]

[[1.099     1.0725625 1.        1.        1.       ]
 [1.099     1.0725625 1.        1.        1.       ]]

[[2.198      2.145125   2.         2.         2.        ]
 [2.4178     2.3596375  2.2        2.2        2.2       ]
 [2.198      2.145125   2.         2.         2.        ]
 [2.36285    2.30600937 2.15       2.15       2.15      ]]
Loss: 68.66557523774414
---------------------------------------------
[[1.    1.   ]
 [1.1   1.1  ]
 [1.    1.   ]
 [1.075 1.075]]

[[1.099     1.0725625 1.        1.        1.       ]
 [1.099     1.0725625 1.        1.        1.       ]]

[[2.198      2.145125   2.

Loss: 92.07187337188886
---------------------------------------------
[[1.04774965 1.04774965]
 [1.42262247 1.42262247]
 [1.39639964 1.39639964]
 [1.23441155 1.23441155]]

[[1.30037168 1.695654   1.23761086 0.64398873 1.02911074]
 [1.30037168 1.695654   1.23761086 0.64398873 1.02911074]]

[[2.72492793 3.55324177 2.59341269 1.34947792 2.15650084]
 [3.69987594 4.82455099 3.52130606 1.83230567 2.92807215]
 [3.63167709 4.73562129 3.45639873 1.79853126 2.87409975]
 [3.21038763 4.18626978 3.05544229 1.58989425 2.54069238]]
Loss: 92.70095835269811
---------------------------------------------
[[1.09115235 1.09115235]
 [1.42262247 1.42262247]
 [1.39639964 1.39639964]
 [1.23441155 1.23441155]]

[[1.30037168 1.695654   1.23761086 0.64398873 1.07025629]
 [1.30037168 1.695654   1.23761086 0.64398873 1.07025629]]

[[2.83780722 3.7004337  2.700844   1.40537963 2.33562532]
 [3.69987594 4.82455099 3.52130606 1.83230567 3.04514129]
 [3.63167709 4.73562129 3.45639873 1.79853126 2.98901099]
 [3.21038763 

 [1.14950798 1.14950798]]

[[1.36835333 1.68206226 1.32997238 0.54551218 0.87217249]
 [1.36835333 1.68206226 1.32997238 0.54551218 0.87217249]]

[[2.56827112 3.15707342 2.49623367 1.02387531 1.63698613]
 [3.98094851 4.89362149 3.86928686 1.58705787 2.53741027]
 [3.68534973 4.53025367 3.58197933 1.4692135  2.34899904]
 [3.14586615 3.86708798 3.05762773 1.25414122 2.00513848]]
Loss: 87.61294868805349
---------------------------------------------
[[0.90545435 0.90545435]
 [1.45464934 1.45464934]
 [1.34663674 1.34663674]
 [1.14950798 1.14950798]]

[[1.36835333 1.68206226 1.31148035 0.54551218 0.87217249]
 [1.36835333 1.68206226 1.31148035 0.54551218 0.87217249]]

[[2.47796294 3.04606117 2.37497117 0.98787276 1.57942475]
 [3.98094851 4.89362149 3.81548803 1.58705787 2.53741027]
 [3.68534973 4.53025367 3.53217524 1.4692135  2.34899904]
 [3.14586615 3.86708798 3.01511426 1.25414122 2.00513848]]
Loss: 87.14065383134509
---------------------------------------------
[[0.90545435 0.90545435]
 [1.

[[2.99470875 3.67815608 2.82000375 1.26895973 1.48032862]
 [3.83353127 4.70841324 3.60989113 1.62439729 1.89497094]
 [3.87661716 4.76133212 3.65046348 1.64265424 1.91626893]
 [3.08074889 3.78383215 2.90102449 1.30541785 1.52285953]]
Loss: 84.78449120673041
---------------------------------------------
[[1.05435176 1.05435176]
 [1.3496773  1.3496773 ]
 [1.36484662 1.36484662]
 [1.15812794 1.15812794]]

[[1.42016586 1.7442737  1.38957303 0.60177247 0.70200889]
 [1.42016586 1.7442737  1.38957303 0.60177247 0.70200889]]

[[2.99470875 3.67815608 2.93019753 1.26895973 1.48032862]
 [3.83353127 4.70841324 3.75095035 1.62439729 1.89497094]
 [3.87661716 4.76133212 3.7931081  1.64265424 1.91626893]
 [3.28946754 4.04018421 3.2186067  1.39385903 1.62603223]]
Loss: 87.4204120202233
---------------------------------------------
[[0.98972289 0.98972289]
 [1.3496773  1.3496773 ]
 [1.36484662 1.36484662]
 [1.15812794 1.15812794]]

[[1.42016586 1.7442737  1.3524295  0.60177247 0.70200889]
 [1.42016586 1.

[[1.13389417 1.13389417]
 [1.32187769 1.32187769]
 [1.32077466 1.32077466]
 [1.15270745 1.15270745]]

[[1.44708352 1.76736875 1.41156064 0.54747434 0.75107292]
 [1.44708352 1.76736875 1.41156064 0.54747434 0.75107292]]

[[3.28167915 4.00801826 3.20112077 1.24155592 1.70327442]
 [3.82573483 4.67249063 3.73182102 1.44738822 1.98565307]
 [3.82254249 4.66859172 3.72870705 1.44618046 1.98399616]
 [3.33612792 4.07451827 3.25423294 1.2621555  1.73153471]]
Loss: 88.11355507051371
---------------------------------------------
[[1.04912143 1.04912143]
 [1.32187769 1.32187769]
 [1.32077466 1.32077466]
 [1.15270745 1.15270745]]

[[1.44708352 1.76736875 1.36110854 0.54747434 0.75107292]
 [1.44708352 1.76736875 1.36110854 0.54747434 0.75107292]]

[[3.03633268 3.70836888 2.8559363  1.14873412 1.5759334 ]
 [3.82573483 4.67249063 3.59843803 1.44738822 1.98565307]
 [3.82254249 4.66859172 3.59543535 1.44618046 1.98399616]
 [3.33612792 4.07451827 3.13791993 1.2621555  1.73153471]]
Loss: 85.52948195522615


[[3.67999564 4.54052071 3.35719434 1.59036824 2.02166377]
 [3.96076173 4.88694076 3.61333224 1.71170575 2.17590706]
 [3.71924436 4.58894731 3.39300025 1.6073302  2.04322568]
 [3.45767927 4.26621819 3.15437909 1.49429071 1.89953076]]
Loss: 93.76450020574288
---------------------------------------------
[[1.24033841 1.24033841]
 [1.33894974 1.33894974]
 [1.25730392 1.25730392]
 [1.1688809  1.1688809 ]]

[[1.47905542 1.82323961 1.34931586 0.63919716 0.81254247]
 [1.47905542 1.82323961 1.34931586 0.63919716 0.81254247]]

[[3.66905848 4.52286824 3.34721657 1.58564158 2.01565527]
 [3.96076173 4.88245241 3.61333224 1.71170575 2.17590706]
 [3.71924436 4.58473264 3.39300025 1.6073302  2.04322568]
 [3.45767927 4.26229994 3.15437909 1.49429071 1.89953076]]
Loss: 93.60644542974003
---------------------------------------------
[[1.24033841 1.24033841]
 [1.33894974 1.33894974]
 [1.2698536  1.2698536 ]
 [1.1688809  1.1688809 ]]

[[1.47905542 1.82323961 1.34931586 0.66311018 0.81254247]
 [1.47905542 1

 [1.0804949  1.0804949 ]]

[[1.49272563 1.79501758 1.4329162  0.59392272 0.76856109]
 [1.49272563 1.79501758 1.4329162  0.59392272 0.76856109]]

[[3.80489962 4.57543006 3.65244769 1.51388594 1.95903236]
 [3.87162892 4.65567271 3.71650333 1.54043606 1.99338934]
 [3.73225462 4.48807372 3.58271339 1.4849821  1.92162956]
 [3.22576485 3.87901468 3.09651727 1.28346095 1.66085268]]
Loss: 90.55775276090962
---------------------------------------------
[[1.27448057 1.27448057]
 [1.3064132  1.3064132 ]
 [1.25014756 1.25014756]
 [1.0804949  1.0804949 ]]

[[1.49924248 1.79501758 1.4329162  0.59392272 0.76856109]
 [1.49924248 1.79501758 1.4329162  0.59392272 0.76856109]]

[[3.82151081 4.57543006 3.65244769 1.51388594 1.95903236]
 [3.91726034 4.69006934 3.74396128 1.55181698 2.00811672]
 [3.74854867 4.48807372 3.58271339 1.4849821  1.92162956]
 [3.23984769 3.87901468 3.09651727 1.28346095 1.66085268]]
Loss: 91.31597991463397
---------------------------------------------
[[1.31448293 1.31448293]
 [1.

[[1.07364739 1.07364739]
 [1.27680901 1.27680901]
 [1.30255468 1.30255468]
 [1.1250989  1.1250989 ]]

[[1.5270406  1.79092792 1.39623549 0.64722668 0.71504202]
 [1.5270406  1.79092792 1.39623549 0.64722668 0.71504202]]

[[3.27900632 3.84565018 2.99812919 1.38978647 1.535406  ]
 [3.8994784  4.5733458  3.56545211 1.65276971 1.82594418]
 [3.97810776 4.66556308 3.63734614 1.68609628 1.86276265]
 [3.43614341 4.02994207 3.14180604 1.45638805 1.60898598]]
Loss: 88.45271699789666
---------------------------------------------
[[1.13224206 1.13224206]
 [1.27680901 1.27680901]
 [1.30255468 1.30255468]
 [1.1250989  1.1250989 ]]

[[1.5270406  1.81609042 1.39623549 0.64722668 0.71504202]
 [1.5270406  1.81609042 1.39623549 0.64722668 0.71504202]]

[[3.4579592  4.11250793 3.1617531  1.46563454 1.6192013 ]
 [3.8994784  4.63760123 3.56545211 1.65276971 1.82594418]
 [3.97810776 4.73111415 3.63734614 1.68609628 1.86276265]
 [3.43614341 4.08656268 3.14180604 1.45638805 1.60898598]]
Loss: 90.32737079908611


Loss: 97.51447861249056
---------------------------------------------
[[1.28821326 1.28821326]
 [1.28040619 1.28040619]
 [1.30907567 1.30907567]
 [1.08359395 1.08359395]]

[[1.53812171 1.81534477 1.44053245 0.61090666 0.98726827]
 [1.53812171 1.81534477 1.44053245 0.61090666 0.98726827]]

[[3.96285754 4.6771024  3.71142598 1.5739561  2.54362415]
 [3.9388411  4.64875737 3.68893332 1.56441733 2.52820881]
 [4.02703541 4.75284736 3.77153196 1.59944608 2.58481775]
 [3.33339874 3.93419322 3.12190448 1.32394951 2.13959585]]
Loss: 100.90751175789357
---------------------------------------------
[[1.31074152 1.31074152]
 [1.28040619 1.28040619]
 [1.30907567 1.30907567]
 [1.08359395 1.08359395]]

[[1.53812171 1.81534477 1.44053245 0.61090666 1.01426253]
 [1.53812171 1.81534477 1.44053245 0.61090666 1.01426253]]

[[4.03215998 4.75889556 3.77633139 1.60148144 2.65887204]
 [3.9388411  4.64875737 3.68893332 1.56441733 2.59733605]
 [4.02703541 4.75284736 3.77153196 1.59944608 2.65549281]
 [3.33339874

Loss: 95.54870381188368
---------------------------------------------
[[1.07893936 1.07893936]
 [1.25564749 1.25564749]
 [1.25617176 1.25617176]
 [1.11019198 1.11019198]]

[[1.57057344 1.75947542 1.42888372 0.66097914 0.90787589]
 [1.57057344 1.75947542 1.42888372 0.66097914 0.90787589]]

[[3.38910699 3.79673455 3.08335777 1.42631282 1.95908605]
 [3.94417319 4.41856178 3.58834852 1.6599136  2.27994416]
 [3.94581999 4.42040665 3.58984676 1.66060666 2.2808961 ]
 [3.48727608 3.906711   3.17267051 1.46762749 2.01583307]]
Loss: 90.92324085617287
---------------------------------------------
[[1.07893936 1.07893936]
 [1.25564749 1.25564749]
 [1.25617176 1.25617176]
 [1.09473738 1.09473738]]

[[1.57057344 1.75947542 1.42888372 0.63650097 0.90787589]
 [1.57057344 1.75947542 1.42888372 0.63650097 0.90787589]]

[[3.38910699 3.79673455 3.08335777 1.3734919  1.95908605]
 [3.94417319 4.41856178 3.58834852 1.59844169 2.27994416]
 [3.94581999 4.42040665 3.58984676 1.59910909 2.2808961 ]
 [3.43873091 

Loss: 96.89720645186836
---------------------------------------------
[[1.2206334  1.2206334 ]
 [1.29789745 1.29789745]
 [1.21347595 1.21347595]
 [1.12644318 1.12644318]]

[[1.55207069 1.91367489 1.36873076 0.69846198 0.97097469]
 [1.55207069 1.91367489 1.36873076 0.69846198 0.97097469]]

[[3.78901863 4.67179095 3.34143694 1.70513205 2.37040826]
 [4.02885717 4.9675075  3.55294431 1.81306406 2.52045114]
 [3.76680092 4.64439692 3.32184372 1.69513365 2.35650887]
 [3.49663888 4.31129205 3.08359485 1.57355548 2.18749563]]
Loss: 99.20675282590835
---------------------------------------------
[[1.2206334  1.2206334 ]
 [1.29427412 1.29427412]
 [1.21347595 1.21347595]
 [1.12644318 1.12644318]]

[[1.55207069 1.91367489 1.36594641 0.69846198 0.97097469]
 [1.55207069 1.91367489 1.36594641 0.69846198 0.97097469]]

[[3.78901863 4.67179095 3.33463961 1.70513205 2.37040826]
 [4.01760986 4.95363977 3.53581818 1.80800254 2.51341482]
 [3.76680092 4.64439692 3.31508625 1.69513365 2.35650887]
 [3.49663888 

[[1.06668633 1.06668633]
 [1.27376039 1.27376039]
 [1.18912601 1.18912601]
 [1.00932184 1.00932184]]

[[1.55335116 1.90448035 1.34364963 0.67203399 0.80743896]
 [1.55335116 1.90448035 1.34364963 0.67203399 0.80743896]]

[[3.3138769  4.06296631 2.86650538 1.43369894 1.72256821]
 [3.95719438 4.85170329 3.42297536 1.71202057 2.05696754]
 [3.69426053 4.52933424 3.19553744 1.5982662  1.92029334]
 [3.13566252 3.84446724 2.71234984 1.35659717 1.62993157]]
Loss: 85.33947362561383
---------------------------------------------
[[1.06668633 1.06668633]
 [1.277085   1.277085  ]
 [1.18912601 1.18912601]
 [1.00932184 1.00932184]]

[[1.55542496 1.90448035 1.34364963 0.67203399 0.80743896]
 [1.55542496 1.90448035 1.34364963 0.67203399 0.80743896]]

[[3.31830108 4.06296631 2.86650538 1.43369894 1.72256821]
 [3.97281978 4.86436659 3.43190957 1.71648906 2.06233638]
 [3.69919255 4.52933424 3.19553744 1.5982662  1.92029334]
 [3.13984878 3.84446724 2.71234984 1.35659717 1.62993157]]
Loss: 85.58963476457612


[[1.0434847  1.0434847 ]
 [1.27265602 1.27265602]
 [1.11898203 1.11898203]
 [1.2328266  1.2328266 ]]

[[1.56210208 1.9756653  1.41227885 0.54453788 0.82394818]
 [1.56210208 1.9756653  1.41227885 0.54453788 0.82394818]]

[[3.26005924 4.12315301 2.94738274 1.13643388 1.71955465]
 [3.97603722 5.02868465 3.59469035 1.38601881 2.09720523]
 [3.49592831 4.42146793 3.16062931 1.21865619 1.84396642]
 [3.85160198 4.87130544 3.48218985 1.34264155 2.03157047]]
Loss: 90.89539887269211
---------------------------------------------
[[1.0434847  1.0434847 ]
 [1.27452763 1.27452763]
 [1.11898203 1.11898203]
 [1.2328266  1.2328266 ]]

[[1.56325651 1.9756653  1.41227885 0.54453788 0.82394818]
 [1.56325651 1.9756653  1.41227885 0.54453788 0.82394818]]

[[3.2624685  4.12315301 2.94738274 1.13643388 1.71955465]
 [3.98482724 5.03608002 3.59997684 1.38805714 2.10028946]
 [3.49851189 4.42146793 3.16062931 1.21865619 1.84396642]
 [3.85444841 4.87130544 3.48218985 1.34264155 2.03157047]]
Loss: 91.04483711305613


[[1.00462329 1.00462329]
 [1.27763351 1.27763351]
 [1.08865333 1.08865333]
 [1.05631443 1.05631443]]

[[1.56232665 1.93694602 1.40671548 0.60914483 0.81035966]
 [1.56232665 1.93694602 1.40671548 0.60914483 0.81035966]]

[[3.13909946 3.89180216 2.82643826 1.22392216 1.62821237]
 [3.99216175 4.94941428 3.59453367 1.55652769 2.07068531]
 [3.40166423 4.21732549 3.062851   1.3262951  1.7644015 ]
 [3.30061637 4.09204808 2.97186773 1.28689695 1.71198921]]
Loss: 83.05221739072265
---------------------------------------------
[[1.00462329 1.00462329]
 [1.27098441 1.27098441]
 [1.08865333 1.08865333]
 [1.05631443 1.05631443]]

[[1.56232665 1.93694602 1.40189674 0.60914483 0.81035966]
 [1.56232665 1.93694602 1.40189674 0.60914483 0.81035966]]

[[3.13909946 3.89180216 2.81675623 1.22392216 1.62821237]
 [3.97138562 4.92365639 3.5635778  1.54842716 2.05990899]
 [3.40166423 4.21732549 3.05235913 1.3262951  1.7644015 ]
 [3.30061637 4.09204808 2.96168753 1.28689695 1.71198921]]
Loss: 82.66507373265593


[[1.12527768 1.12527768]
 [1.27723874 1.27723874]
 [1.15036438 1.15036438]
 [0.90648055 0.90648055]]

[[1.5720132  1.96910896 1.36045726 0.68843118 0.9086038 ]
 [1.5720132  1.96910896 1.36045726 0.68843118 0.9086038 ]]

[[3.53790273 4.43158871 3.06178436 1.54935248 2.04486315]
 [4.01567233 5.03004449 3.47525742 1.75858195 2.32100795]
 [3.61677599 4.53038561 3.13004314 1.58389342 2.0904509 ]
 [2.84999878 3.56991793 2.46645608 1.24809895 1.64726334]]
Loss: 87.89439686718252
---------------------------------------------
[[1.12527768 1.12527768]
 [1.27723874 1.27723874]
 [1.15036438 1.15036438]
 [0.89959675 0.89959675]]

[[1.5720132  1.96718346 1.36045726 0.68843118 0.9086038 ]
 [1.5720132  1.96718346 1.36045726 0.68843118 0.9086038 ]]

[[3.53790273 4.42725527 3.06178436 1.54935248 2.04486315]
 [4.01567233 5.02512584 3.47525742 1.75858195 2.32100795]
 [3.61677599 4.52595556 3.13004314 1.58389342 2.0904509 ]
 [2.82835593 3.53934368 2.44772584 1.2386209  1.63475405]]
Loss: 87.7356240626854
-

 [2.89922194 3.53149742 2.72252502 1.25095126 2.02382586]]
Loss: 100.6804956313971
---------------------------------------------
[[1.23250352 1.23250352]
 [1.20362442 1.20362442]
 [1.2878626  1.2878626 ]
 [0.91562976 0.91562976]]

[[1.58318464 1.92845273 1.48195033 0.68310976 1.10515513]
 [1.58318464 1.92845273 1.48195033 0.68310976 1.10515513]]

[[3.90256128 4.75364955 3.65301799 1.68387038 2.72421518]
 [3.81111938 4.64226558 3.5674232  1.64441518 2.6603834 ]
 [4.07784858 4.96716429 3.81709681 1.75950304 2.84657593]
 [2.89922194 3.53149742 2.71383565 1.25095126 2.02382586]]
Loss: 100.18029797587654
---------------------------------------------
[[1.23250352 1.23250352]
 [1.20362442 1.20362442]
 [1.20240229 1.20240229]
 [0.91562976 0.91562976]]

[[1.58318464 1.92845273 1.48195033 0.68310976 1.02353113]
 [1.58318464 1.92845273 1.48195033 0.68310976 1.02353113]]

[[3.90256128 4.75364955 3.65301799 1.68387038 2.52301144]
 [3.81111938 4.64226558 3.5674232  1.64441518 2.46389411]
 [3.8072496

[[3.61755374 4.21404804 3.19434787 1.5746255  2.38440065]
 [3.8827982  4.52302835 3.42856223 1.6900794  2.55922847]
 [4.05133491 4.71935488 3.57738238 1.76343897 2.67031432]
 [3.01575268 3.51301668 2.66294955 1.3126774  1.98774176]]
Loss: 93.49096765696423
---------------------------------------------
[[1.1085152  1.1085152 ]
 [1.1897932  1.1897932 ]
 [1.24143735 1.24143735]
 [0.91300345 0.91300345]]

[[1.63171138 1.9007624  1.44082276 0.69668707 1.07549298]
 [1.63171138 1.9007624  1.44082276 0.69668707 1.07549298]]

[[3.61755374 4.21404804 3.19434787 1.54457643 2.38440065]
 [3.8827982  4.52302835 3.42856223 1.65782708 2.55922847]
 [4.05133491 4.71935488 3.57738238 1.72978671 2.67031432]
 [2.97951624 3.47080526 2.6309523  1.2721554  1.96385761]]
Loss: 93.05825916137344
---------------------------------------------
[[1.1085152  1.1085152 ]
 [1.1897932  1.1897932 ]
 [1.24143735 1.24143735]
 [0.91577806 0.91577806]]

[[1.63171138 1.90161622 1.44082276 0.69668707 1.07549298]
 [1.63171138 1

[[1.00759974 1.00759974]
 [1.22127758 1.22127758]
 [1.19571126 1.19571126]
 [0.91584857 0.91584857]]

[[1.63479265 1.93930235 1.42538942 0.67696785 1.01572767]
 [1.63479265 1.93930235 1.42538942 0.67696785 1.01572767]]

[[3.29443332 3.9080811  2.87244402 1.36422526 2.04689389]
 [3.99307121 4.73685294 3.48159226 1.65353131 2.48097086]
 [3.90947996 4.63769131 3.40870835 1.61891616 2.42903403]
 [2.99444504 3.55221458 2.61088173 1.24000008 1.86050548]]
Loss: 88.93457833892836
---------------------------------------------
[[1.00759974 1.00759974]
 [1.22127758 1.22127758]
 [1.20861034 1.20861034]
 [0.91584857 0.91584857]]

[[1.63479265 1.93930235 1.42538942 0.69894155 1.01572767]
 [1.63479265 1.93930235 1.42538942 0.69894155 1.01572767]]

[[3.29443332 3.9080811  2.87244402 1.40850666 2.04689389]
 [3.99307121 4.73685294 3.48159226 1.70720329 2.48097086]
 [3.95165459 4.68772173 3.44548076 1.68949597 2.45523793]
 [2.99444504 3.55221458 2.61088173 1.28024925 1.86050548]]
Loss: 89.81955597144656


 [0.9725293  0.9725293 ]]

[[1.65196394 1.9256248  1.46273609 0.70719535 1.07369856]
 [1.65196394 1.9256248  1.46273609 0.70719535 1.07369856]]

[[3.53794799 4.12403699 3.13268595 1.51457323 2.29949914]
 [3.93256511 4.58402555 3.48210079 1.68350633 2.55598163]
 [3.40049336 3.96381192 3.01097637 1.45572977 2.21016012]
 [3.21316667 3.74545309 2.84510743 1.37553639 2.08840662]]
Loss: 86.16000395554141
---------------------------------------------
[[1.07083088 1.07083088]
 [1.19157875 1.19157875]
 [1.02922748 1.02922748]
 [0.9725293  0.9725293 ]]

[[1.65196394 1.9256248  1.46357434 0.70719535 1.07369856]
 [1.65196394 1.9256248  1.46357434 0.70719535 1.07369856]]

[[3.53794799 4.12403699 3.13448119 1.51457323 2.29949914]
 [3.93689025 4.58906719 3.48792817 1.68535789 2.55879277]
 [3.40049336 3.96381192 3.01270186 1.45572977 2.21016012]
 [3.21316667 3.74545309 2.84673787 1.37553639 2.08840662]]
Loss: 86.23682871431336
---------------------------------------------
[[1.07083088 1.07083088]
 [1.

[[0.98462591 0.98462591]
 [1.15199885 1.15199885]
 [1.17799491 1.17799491]
 [0.97218516 0.97218516]]

[[1.66273199 1.96193439 1.52454606 0.68585438 1.0679651 ]
 [1.66273199 1.96193439 1.52454606 0.68585438 1.0679651 ]]

[[3.27433801 3.86354288 3.00221512 1.35061999 2.10309223]
 [3.83093067 4.52029231 3.51255061 1.58020691 2.46058913]
 [3.91737963 4.62229743 3.59181499 1.61586593 2.5161149 ]
 [3.23296674 3.814727   2.96428212 1.3335549  2.07651965]]
Loss: 89.83594035961502
---------------------------------------------
[[0.90822976 0.90822976]
 [1.15199885 1.15199885]
 [1.17799491 1.17799491]
 [0.97218516 0.97218516]]

[[1.66273199 1.96193439 1.48961208 0.68585438 1.0679651 ]
 [1.66273199 1.96193439 1.48961208 0.68585438 1.0679651 ]]

[[3.02028535 3.5637744  2.70582005 1.24582671 1.93991537]
 [3.83093067 4.52029231 3.43206281 1.58020691 2.46058913]
 [3.91737963 4.62229743 3.50951089 1.61586593 2.5161149 ]
 [3.23296674 3.814727   2.89635753 1.3335549  2.07651965]]
Loss: 87.81451268512096


 [1.68912881 2.05966208 1.49725695 0.74264262 1.03900433]]

[[3.74530864 4.56689277 3.31987079 1.64666293 2.30378635]
 [3.89545421 4.74997479 3.45296098 1.71267595 2.39614277]
 [4.07613123 4.97028577 3.61311451 1.79211244 2.50727948]
 [3.25140474 3.96464437 2.88207052 1.42951307 1.99997986]]
Loss: 97.61300543959533
---------------------------------------------
[[1.0098417  1.0098417 ]
 [1.15309566 1.15309566]
 [1.20657797 1.20657797]
 [0.9624502  0.9624502 ]]

[[1.68912881 2.05966208 1.44555382 0.74264262 1.03900433]
 [1.68912881 2.05966208 1.44555382 0.74264262 1.03900433]]

[[3.41150542 4.1598653  2.91956104 1.49990296 2.0984598 ]
 [3.89545421 4.74997479 3.33372366 1.71267595 2.39614277]
 [4.07613123 4.97028577 3.48834678 1.79211244 2.50727948]
 [3.25140474 3.96464437 2.78254713 1.42951307 1.99997986]]
Loss: 93.67688686844193
---------------------------------------------
[[1.0098417  1.0098417 ]
 [1.15309566 1.15309566]
 [1.20657797 1.20657797]
 [0.91459968 0.91459968]]

[[1.68912881

Loss: 90.93852561383353
---------------------------------------------
[[0.76566188 0.76566188]
 [1.16548986 1.16548986]
 [1.16021079 1.16021079]
 [0.93334691 0.93334691]]

[[1.70327    2.01157667 1.49833615 0.67377775 0.9919252 ]
 [1.70327    2.01157667 1.49833615 0.67377775 0.9919252 ]]

[[2.60825783 3.08037516 2.29443777 1.03177189 1.51895864]
 [3.97028784 4.68894443 3.4925912  1.57056228 2.31215753]
 [3.95230447 4.66770592 3.47677156 1.56344844 2.30168465]
 [3.17948357 3.75499772 2.79693483 1.25773676 1.85162063]]
Loss: 86.09240235246568
---------------------------------------------
[[0.839116   0.839116  ]
 [1.16548986 1.16548986]
 [1.16021079 1.16021079]
 [0.93334691 0.93334691]]

[[1.70327    2.01157667 1.49833615 0.67377775 1.04794959]
 [1.70327    2.01157667 1.49833615 0.67377775 1.04794959]]

[[2.8584822  3.37589232 2.51455567 1.13075538 1.75870254]
 [3.97028784 4.68894443 3.4925912  1.57056228 2.44274926]
 [3.95230447 4.66770592 3.47677156 1.56344844 2.43168486]
 [3.17948357 

Loss: 102.35268576906788
---------------------------------------------
[[1.05407366 1.05407366]
 [1.17425623 1.17425623]
 [1.21324413 1.21324413]
 [0.99198617 0.99198617]]

[[1.70529588 2.04180464 1.61128307 0.7156097  1.14175078]
 [1.70529588 2.04180464 1.61128307 0.7156097  1.14175078]]

[[3.59501495 4.304425   3.3968221  1.50861069 2.40697885]
 [4.00490862 4.79520364 3.78411837 1.68061831 2.68141592]
 [4.13788044 4.954415   3.90975947 1.73641855 2.77044486]
 [3.38325987 4.05088395 3.19674106 1.41974987 2.26520197]]
Loss: 102.97477908598997
---------------------------------------------
[[1.08792778 1.08792778]
 [1.17425623 1.17425623]
 [1.21324413 1.21324413]
 [0.99198617 0.99198617]]

[[1.70529588 2.04180464 1.61128307 0.7156097  1.16980382]
 [1.70529588 2.04180464 1.61128307 0.7156097  1.16980382]]

[[3.71047753 4.44267199 3.50591924 1.55706336 2.54532416]
 [4.00490862 4.79520364 3.78411837 1.68061831 2.74729885]
 [4.13788044 4.954415   3.90975947 1.73641855 2.83851525]
 [3.3832598

[[0.98395932 0.98395932]
 [1.15702323 1.15702323]
 [1.18225624 1.18225624]
 [0.95700801 0.95700801]]

[[1.70823513 2.08703639 1.53445217 0.72642091 1.12622047]
 [1.70823513 2.08703639 1.53445217 0.72642091 1.12622047]]

[[3.36166776 4.10711782 3.01967703 1.42953724 2.21631026]
 [3.95293546 4.82949918 3.55079361 1.68097172 2.6061265 ]
 [4.03914329 4.93482361 3.62823131 1.7176313  2.66296237]
 [3.26958942 3.99462111 2.93696605 1.39038126 2.15560404]]
Loss: 96.38339272722801
---------------------------------------------
[[0.98395932 0.98395932]
 [1.15702323 1.15702323]
 [1.19251217 1.19251217]
 [0.95700801 0.95700801]]

[[1.70823513 2.08703639 1.53445217 0.74236888 1.12622047]
 [1.70823513 2.08703639 1.53445217 0.74236888 1.12622047]]

[[3.36166776 4.10711782 3.01967703 1.46092155 2.21631026]
 [3.95293546 4.82949918 3.55079361 1.71787607 2.6061265 ]
 [4.07418236 4.97763259 3.65970577 1.77056783 2.68606324]
 [3.26958942 3.99462111 2.93696605 1.42090593 2.15560404]]
Loss: 97.17063577288799


[[1.00551492 1.00551492]
 [1.16181813 1.16181813]
 [1.02898492 1.02898492]
 [0.88057049 0.88057049]]

[[1.70797677 2.10766859 1.53253219 0.76222014 1.01433357]
 [1.70797677 2.10766859 1.53253219 0.76222014 1.01433357]]

[[3.43479226 4.23858443 3.08196796 1.53284744 2.03985507]
 [3.96871675 4.89745514 3.56104735 1.77112234 2.35694225]
 [3.51496469 4.33751839 3.15390502 1.56862605 2.08746789]
 [3.00798789 3.71190153 2.69900524 1.34237712 1.78638441]]
Loss: 86.63115038658904
---------------------------------------------
[[1.00551492 1.00551492]
 [1.15714028 1.15714028]
 [1.02898492 1.02898492]
 [0.88057049 0.88057049]]

[[1.70797677 2.10766859 1.52982972 0.76222014 1.01433357]
 [1.70797677 2.10766859 1.52982972 0.76222014 1.01433357]]

[[3.43479226 4.23858443 3.07653322 1.53284744 2.03985507]
 [3.95273742 4.87773642 3.54045516 1.76399124 2.34745244]
 [3.51496469 4.33751839 3.14834342 1.56862605 2.08746789]
 [3.00798789 3.71190153 2.69424581 1.34237712 1.78638441]]
Loss: 86.33333317019326


[[3.51358899 4.31302069 3.23408879 1.708489   2.26838373]
 [3.96255015 4.86413203 3.64733583 1.92679717 2.55823442]
 [3.71156874 4.5560459  3.41631957 1.804757   2.39620006]
 [4.02182753 4.93689654 3.70189779 1.9556209  2.59650408]]
Loss: 104.16497202546235
---------------------------------------------
[[0.91491872 0.91491872]
 [1.14286831 1.14286831]
 [1.07048091 1.07048091]
 [1.15996494 1.15996494]]

[[1.73359875 2.12803697 1.55361396 0.84296553 1.11921662]
 [1.73359875 2.12803697 1.55361396 0.84296553 1.11921662]]

[[3.1722039  3.89396171 2.84286099 1.54248988 2.04798448]
 [3.96255015 4.86413203 3.55115233 1.92679717 2.55823442]
 [3.71156874 4.5560459  3.32622818 1.804757   2.39620006]
 [4.02182753 4.93689654 3.60427545 1.9556209  2.59650408]]
Loss: 100.6749103255179
---------------------------------------------
[[0.91491872 0.91491872]
 [1.14286831 1.14286831]
 [1.07048091 1.07048091]
 [1.00707649 1.00707649]]

[[1.73359875 2.0884492  1.55361396 0.84296553 1.11921662]
 [1.73359875 

In [40]:
model = SVD_decomposer(test_input)
print (model.P)
print()
print (model.Q)

[[1.]
 [1.]
 [1.]
 [1.]]

[[1. 1. 1. 1.]]


In [35]:
model.SGD()
print (model.P)
print()
print (model.Q)

[[0.]
 [0.]
 [0.]
 [0.]]

[[0. 0. 0. 0.]]
